version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - "5000:3000"
        volumes: 
            - "/app/node_modules"
            - "./:/app"
